import type { Metadata } from 'next';
import { UserProvider } from '@/context/UserContext';

// import HeaderFunc from '@/app/components/Header/header';

import './assets/css/style.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={{ minHeight: '100vh' }}>
                {/* <HeaderFunc /> */}
                <UserProvider>{children}</UserProvider>
            </body>
        </html>
    );
}
