import type { Metadata } from 'next';
import { UserProvider } from '@/context/UserContext';
import { Provider } from 'react-redux';
// import HeaderFunc from '@/app/components/Header/header';
import store from '@/redux/store';

import './assets/css/style.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={{ minHeight: '100vh' }}>
                {/* <HeaderFunc /> */}


                <Provider store={store}> >
                    {children}
                </Provider>
                {/* <UserProvider>{children}</UserProvider> */}
            </body>
        </html>
    );
}
