import type { Metadata } from 'next';
import { UserProvider } from '@/context/UserContext';


import '../../public/css/style.css';

export const metadata: Metadata = {
    title: 'Business System',
    description: 'Generated by Business System',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={{ minHeight: '100vh' }}>
                {/* <HeaderFunc /> */}
                <UserProvider>{children}</UserProvider>
            </body>
        </html>
    );
}
